/* soapClient.c
   Generated by gSOAP 2.8.9 from boardId.h

Copyright(C) 2000-2012, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapClient.c ver 2.8.9 2012-07-13 00:51:44 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns2__CheckSNtest(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__CheckSNtest *ns1__CheckSNtest, struct _ns1__CheckSNtestResponse *ns1__CheckSNtestResponse)
{	struct __ns2__CheckSNtest soap_tmp___ns2__CheckSNtest;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.2.1/web/Service1.asmx";
	if (!soap_action)
		soap_action = "http://tempuri.org/CheckSNtest";
	soap->encodingStyle = NULL;
	soap_tmp___ns2__CheckSNtest.ns1__CheckSNtest = ns1__CheckSNtest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns2__CheckSNtest(soap, &soap_tmp___ns2__CheckSNtest);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns2__CheckSNtest(soap, &soap_tmp___ns2__CheckSNtest, "-ns2:CheckSNtest", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns2__CheckSNtest(soap, &soap_tmp___ns2__CheckSNtest, "-ns2:CheckSNtest", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__CheckSNtestResponse)
		return soap_closesock(soap);
	soap_default__ns1__CheckSNtestResponse(soap, ns1__CheckSNtestResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__CheckSNtestResponse(soap, ns1__CheckSNtestResponse, "ns1:CheckSNtestResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns2__CheckSN(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__CheckSN *ns1__CheckSN, struct _ns1__CheckSNResponse *ns1__CheckSNResponse)
{	struct __ns2__CheckSN soap_tmp___ns2__CheckSN;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.2.1/web/Service1.asmx";
	if (!soap_action)
		soap_action = "http://tempuri.org/CheckSN";
	soap->encodingStyle = NULL;
	soap_tmp___ns2__CheckSN.ns1__CheckSN = ns1__CheckSN;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns2__CheckSN(soap, &soap_tmp___ns2__CheckSN);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns2__CheckSN(soap, &soap_tmp___ns2__CheckSN, "-ns2:CheckSN", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns2__CheckSN(soap, &soap_tmp___ns2__CheckSN, "-ns2:CheckSN", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__CheckSNResponse)
		return soap_closesock(soap);
	soap_default__ns1__CheckSNResponse(soap, ns1__CheckSNResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__CheckSNResponse(soap, ns1__CheckSNResponse, "ns1:CheckSNResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns2__getSource(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getSource *ns1__getSource, struct _ns1__getSourceResponse *ns1__getSourceResponse)
{	struct __ns2__getSource soap_tmp___ns2__getSource;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.2.1/web/Service1.asmx";
	if (!soap_action)
		soap_action = "http://tempuri.org/getSource";
	soap->encodingStyle = NULL;
	soap_tmp___ns2__getSource.ns1__getSource = ns1__getSource;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns2__getSource(soap, &soap_tmp___ns2__getSource);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns2__getSource(soap, &soap_tmp___ns2__getSource, "-ns2:getSource", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns2__getSource(soap, &soap_tmp___ns2__getSource, "-ns2:getSource", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getSourceResponse)
		return soap_closesock(soap);
	soap_default__ns1__getSourceResponse(soap, ns1__getSourceResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__getSourceResponse(soap, ns1__getSourceResponse, "ns1:getSourceResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns2__getSourceTest(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getSourceTest *ns1__getSourceTest, struct _ns1__getSourceTestResponse *ns1__getSourceTestResponse)
{	struct __ns2__getSourceTest soap_tmp___ns2__getSourceTest;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.2.1/web/Service1.asmx";
	if (!soap_action)
		soap_action = "http://tempuri.org/getSourceTest";
	soap->encodingStyle = NULL;
	soap_tmp___ns2__getSourceTest.ns1__getSourceTest = ns1__getSourceTest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns2__getSourceTest(soap, &soap_tmp___ns2__getSourceTest);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns2__getSourceTest(soap, &soap_tmp___ns2__getSourceTest, "-ns2:getSourceTest", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns2__getSourceTest(soap, &soap_tmp___ns2__getSourceTest, "-ns2:getSourceTest", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getSourceTestResponse)
		return soap_closesock(soap);
	soap_default__ns1__getSourceTestResponse(soap, ns1__getSourceTestResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__getSourceTestResponse(soap, ns1__getSourceTestResponse, "ns1:getSourceTestResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns2__updateM2(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__updateM2 *ns1__updateM2, struct _ns1__updateM2Response *ns1__updateM2Response)
{	struct __ns2__updateM2 soap_tmp___ns2__updateM2;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.2.1/web/Service1.asmx";
	if (!soap_action)
		soap_action = "http://tempuri.org/updateM2";
	soap->encodingStyle = NULL;
	soap_tmp___ns2__updateM2.ns1__updateM2 = ns1__updateM2;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns2__updateM2(soap, &soap_tmp___ns2__updateM2);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns2__updateM2(soap, &soap_tmp___ns2__updateM2, "-ns2:updateM2", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns2__updateM2(soap, &soap_tmp___ns2__updateM2, "-ns2:updateM2", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__updateM2Response)
		return soap_closesock(soap);
	soap_default__ns1__updateM2Response(soap, ns1__updateM2Response);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__updateM2Response(soap, ns1__updateM2Response, "ns1:updateM2Response", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns3__CheckSNtest(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__CheckSNtest *ns1__CheckSNtest, struct _ns1__CheckSNtestResponse *ns1__CheckSNtestResponse)
{	struct __ns3__CheckSNtest soap_tmp___ns3__CheckSNtest;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.2.1/web/Service1.asmx";
	if (!soap_action)
		soap_action = "http://tempuri.org/CheckSNtest";
	soap->encodingStyle = NULL;
	soap_tmp___ns3__CheckSNtest.ns1__CheckSNtest = ns1__CheckSNtest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns3__CheckSNtest(soap, &soap_tmp___ns3__CheckSNtest);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__CheckSNtest(soap, &soap_tmp___ns3__CheckSNtest, "-ns3:CheckSNtest", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__CheckSNtest(soap, &soap_tmp___ns3__CheckSNtest, "-ns3:CheckSNtest", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__CheckSNtestResponse)
		return soap_closesock(soap);
	soap_default__ns1__CheckSNtestResponse(soap, ns1__CheckSNtestResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__CheckSNtestResponse(soap, ns1__CheckSNtestResponse, "ns1:CheckSNtestResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns3__CheckSN(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__CheckSN *ns1__CheckSN, struct _ns1__CheckSNResponse *ns1__CheckSNResponse)
{	struct __ns3__CheckSN soap_tmp___ns3__CheckSN;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.2.1/web/Service1.asmx";
	if (!soap_action)
		soap_action = "http://tempuri.org/CheckSN";
	soap->encodingStyle = NULL;
	soap_tmp___ns3__CheckSN.ns1__CheckSN = ns1__CheckSN;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns3__CheckSN(soap, &soap_tmp___ns3__CheckSN);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__CheckSN(soap, &soap_tmp___ns3__CheckSN, "-ns3:CheckSN", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__CheckSN(soap, &soap_tmp___ns3__CheckSN, "-ns3:CheckSN", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__CheckSNResponse)
		return soap_closesock(soap);
	soap_default__ns1__CheckSNResponse(soap, ns1__CheckSNResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__CheckSNResponse(soap, ns1__CheckSNResponse, "ns1:CheckSNResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns3__getSource(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getSource *ns1__getSource, struct _ns1__getSourceResponse *ns1__getSourceResponse)
{	struct __ns3__getSource soap_tmp___ns3__getSource;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.2.1/web/Service1.asmx";
	if (!soap_action)
		soap_action = "http://tempuri.org/getSource";
	soap->encodingStyle = NULL;
	soap_tmp___ns3__getSource.ns1__getSource = ns1__getSource;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns3__getSource(soap, &soap_tmp___ns3__getSource);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__getSource(soap, &soap_tmp___ns3__getSource, "-ns3:getSource", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__getSource(soap, &soap_tmp___ns3__getSource, "-ns3:getSource", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getSourceResponse)
		return soap_closesock(soap);
	soap_default__ns1__getSourceResponse(soap, ns1__getSourceResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__getSourceResponse(soap, ns1__getSourceResponse, "ns1:getSourceResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns3__getSourceTest(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getSourceTest *ns1__getSourceTest, struct _ns1__getSourceTestResponse *ns1__getSourceTestResponse)
{	struct __ns3__getSourceTest soap_tmp___ns3__getSourceTest;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.2.1/web/Service1.asmx";
	if (!soap_action)
		soap_action = "http://tempuri.org/getSourceTest";
	soap->encodingStyle = NULL;
	soap_tmp___ns3__getSourceTest.ns1__getSourceTest = ns1__getSourceTest;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns3__getSourceTest(soap, &soap_tmp___ns3__getSourceTest);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__getSourceTest(soap, &soap_tmp___ns3__getSourceTest, "-ns3:getSourceTest", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__getSourceTest(soap, &soap_tmp___ns3__getSourceTest, "-ns3:getSourceTest", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getSourceTestResponse)
		return soap_closesock(soap);
	soap_default__ns1__getSourceTestResponse(soap, ns1__getSourceTestResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__getSourceTestResponse(soap, ns1__getSourceTestResponse, "ns1:getSourceTestResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns3__updateM2(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__updateM2 *ns1__updateM2, struct _ns1__updateM2Response *ns1__updateM2Response)
{	struct __ns3__updateM2 soap_tmp___ns3__updateM2;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.2.1/web/Service1.asmx";
	if (!soap_action)
		soap_action = "http://tempuri.org/updateM2";
	soap->encodingStyle = NULL;
	soap_tmp___ns3__updateM2.ns1__updateM2 = ns1__updateM2;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns3__updateM2(soap, &soap_tmp___ns3__updateM2);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns3__updateM2(soap, &soap_tmp___ns3__updateM2, "-ns3:updateM2", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns3__updateM2(soap, &soap_tmp___ns3__updateM2, "-ns3:updateM2", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__updateM2Response)
		return soap_closesock(soap);
	soap_default__ns1__updateM2Response(soap, ns1__updateM2Response);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__updateM2Response(soap, ns1__updateM2Response, "ns1:updateM2Response", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.c */
